# generated by stubbs:add-option
# Thu May 24 18:06:53 PDT 2012

# print USAGE and exit
rerun_option_error() {
    [ -z "$USAGE"  ] && echo "$USAGE" >&2
    [ -z "$SYNTAX" ] && echo "$SYNTAX $*" >&2
    return 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [file url]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
          -f|--file) rerun_option_check $# ; FILE=$2 ; shift ;;
  -u|--url) rerun_option_check $# ; URL=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_error
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$URL" ] && URL="http://localhost:8080"
# Check required options are set
[ -z "$FILE" ] && { echo "missing required option: --file" ; return 2 ; }
[ -z "$URL" ] && { echo "missing required option: --url" ; return 2 ; }
#
return 0
