# generated by stubbs:add-option
# Fri May 25 14:45:50 PDT 2012

# print USAGE and exit
rerun_option_error() {
    [ -z "$USAGE"  ] && echo "$USAGE" >&2
    [ -z "$SYNTAX" ] && echo "$SYNTAX $*" >&2
    return 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [action attributes description file id status tags typeid cfg]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
  -a|--action) rerun_option_check $# ; ACTION=$2 ; shift ;;
  -A|--attributes) rerun_option_check $# ; ATTRIBUTES=$2 ; shift ;;
  -d|--description) rerun_option_check $# ; DESCRIPTION=$2 ; shift ;;
  -D|--depth) rerun_option_check $# ; DEPTH=$2 ; shift ;;
  -f|--file) rerun_option_check $# ; FILE=$2 ; shift ;;
  -i|--id) rerun_option_check $# ; ID=$2 ; shift ;;
  -S|--status) rerun_option_check $# ; STATUS=$2 ; shift ;;
  -n|--name) rerun_option_check $# ; NAME=$2 ; shift ;;
  -T|--tags) rerun_option_check $# ; TAGS=$2 ; shift ;;
  -t|--typeid) rerun_option_check $# ; TYPEID=$2 ; shift ;;
  -C|--cfg) rerun_option_check $# ; CFG=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_error
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$ACTION" ] && ACTION="get"
[ -z "$CFG" ] && CFG="$HOME/.yanarc"
[ -z "$DEPTH" ] && DEPTH=1
[ -z "$STATUS" ] && STATUS=DEV
# Check required options are set
[ -z "$ACTION" ] && { echo "missing required option: --action" ; return 2 ; }
[ -z "$CFG" ] && { echo "missing required option: --cfg" ; return 2 ; }
#
return 0
